### ISSUE TITLE
bad argument #2 to 'G_XP_Set'

### ISSUE THREAD

**Issue by g1ocke** [Zelly/ZellyLuas#2] opened 2015-08-30 12:18 UTC
Hi,
i always get the error message

"Lua API: et_ClientBegin error running lua script: [string "ZXpSave.lua"]:199: bad argument #2 to 'G_XP_Set' (number has no integer representation)"

and my points are not saved...

**Comment by Zelly** [comment] 2015-08-30 16:55
Thanks for reporting I am aware of the issue (Fixed in LuaESMod)  
Will work on fixing it here.  
The issue is the value returned from et.gentity_get( client , "sess.skillpoints" , skill ) is a float value.  
And the xp value needed to be set in et.G_XP_Set() is required to be an int value.  
With lua 5.2 and lower the value automatically got converted to an int and was no issue.  (Though XP was not exact as it was always rounded down I believe , meaning if you had 7 values of 10.9 would not add up to 76.3 or 77 they would only add up to 70 )  
I can add a fix in the lua where it converts it to an integer before sending, but once again I will have to round down.  
The real fix needs to be at the api level ( Which I already notified them, however you won't see a fix until next mod release )  
In the meantime we can make due. :+1:

**Comment by Zelly** [comment] 2015-08-30 17:03
You can now download new version tell me if I missed anything. :laughing:

**Comment by g1ocke** [comment] 2015-08-30 17:22
now I get the following error...

Lua API: et_ClientBegin error running lua script: [string "ZXpSave.lua"]:205: attempt to call a nil value (global 'int')

Thanks for the help

**Comment by Zelly** [comment] 2015-08-30 19:33
lol my bad I forgot to add the underscors :panda_face: will update it in a few minutes.

**Comment by Zelly** [comment] 2015-08-30 19:40
Give that a try, apologies am working on same sort of thing in 3 different projects am getting confused lol.

**Comment by klassifyed** [comment] 2015-12-21 02:45
I believe this issue can now be closed.

**Closed as completed** 2015-12-21 18:51 UTC
